CREATE TABLE IF NOT EXISTS detected_animals (
    time_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    animal_id SERIAL PRIMARY KEY,
    animal_type VARCHAR(255) NOT NULL,
    animal_name VARCHAR(255) NOT NULL,
    is_endangered BOOLEAN NOT NULL,
    is_threat BOOLEAN NOT NULL
);

INSERT INTO detected_animals (animal_type, animal_name, is_endangered, is_threat)
VALUES
    ('Mammal', 'Amur Leopard', TRUE, TRUE),
    ('Mammal', 'Amur Leopard', TRUE, TRUE),
    ('Mammal', 'Amur Leopard', TRUE, TRUE),
    ('Mammal', 'Amur Leopard', TRUE, TRUE),
    ('Mammal', 'Amur Leopard', TRUE, TRUE),
    ('Mammal', 'Amur Leopard', TRUE, TRUE),
    ('Mammal', 'Amur Leopard', TRUE, TRUE),
    ('Mammal', 'Amur Leopard', TRUE, TRUE),
    ('Mammal', 'Amur Leopard', TRUE, TRUE),
    ('Mammal', 'Amur Leopard', TRUE, TRUE),
    ('Mammal', 'Black Rhino', TRUE, FALSE),
    ('Mammal', 'Black Rhino', TRUE, FALSE),
    ('Mammal', 'Black Rhino', TRUE, FALSE),
    ('Mammal', 'Black Rhino', TRUE, FALSE),
    ('Mammal', 'Black Rhino', TRUE, FALSE),
    ('Mammal', 'Orangutan', TRUE, FALSE),
    ('Mammal', 'Orangutan', TRUE, FALSE),
    ('Mammal', 'Orangutan', TRUE, FALSE),
    ('Mammal', 'Orangutan', TRUE, FALSE),
    ('Mammal', 'Orangutan', TRUE, FALSE),
    ('Mammal', 'Orangutan', TRUE, FALSE),
    ('Mammal', 'Orangutan', TRUE, FALSE),
    ('Mammal', 'Giant Panda', TRUE, FALSE),
    ('Mammal', 'Giant Panda', TRUE, FALSE),
    ('Mammal', 'Giant Panda', TRUE, FALSE),
    ('Mammal', 'Giant Panda', TRUE, FALSE),
    ('Mammal', 'Giant Panda', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Asian Elephant', TRUE, FALSE),
    ('Mammal', 'Dog', FALSE, FALSE),
    ('Mammal', 'Dog', FALSE, FALSE),
    ('Mammal', 'Dog', FALSE, FALSE),
    ('Mammal', 'Dog', FALSE, FALSE),
    ('Mammal', 'Dog', FALSE, FALSE),
    ('Mammal', 'Dog', FALSE, FALSE),
    ('Mammal', 'Dog', FALSE, FALSE),
    ('Mammal', 'Dog', FALSE, FALSE),
    ('Mammal', 'Dog', FALSE, FALSE),
    ('Mammal', 'Dog', FALSE, FALSE),
    ('Mammal', 'Cat', FALSE, FALSE),
    ('Mammal', 'Cat', FALSE, FALSE),
    ('Mammal', 'Cat', FALSE, FALSE),
    ('Mammal', 'Cat', FALSE, FALSE),
    ('Mammal', 'Cat', FALSE, FALSE),
    ('Mammal', 'Cat', FALSE, FALSE),
    ('Mammal', 'Cat', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Fox', FALSE, FALSE),
    ('Mammal', 'Snow Leopard', TRUE, TRUE);


-- Add sql functions to get statistics about the animals

